### ISSUE TITLE
Add EXPOSE to Dockerfile for better Gitlab CI compatibility

### ISSUE THREAD

**Issue by filipsuk** [koxudaxi/local-data-api#133]
**Is your feature request related to a problem? Please describe.**
Incompatibility with Gitlab CI pipelines. It uses exposed port to determine health.

**Describe the solution you'd like**
Add `EXPOSE` to Dockerfile.

**Describe alternatives you've considered**
Own fork of Dockerfile - hard to maintain.

**Additional context**
Extract from Gitlab pipeline when using local-data-api as a service.

```yaml
e2e:
  stage: quality
  services:
    - name: postgres:10.12-alpine
      alias: db
    - name: koxudaxi/local-data-api:0.6.10
      alias: local-data-api
```

Result:
```
Using docker image sha256:3b192751cea87d9926ea4c5190929eb9f6a12a637a85127cc0287f161878ec73 for koxudaxi/local-data-api:0.6.10 ...
Waiting for services to be up and running...
*** WARNING: Service runner-3q1dx6xf-project-19117306-concurrent-0-4a702edf8cdc3559-koxudaxi__local-data-api-1 probably didn't start properly.
Health check error:
service "runner-3q1dx6xf-project-19117306-concurrent-0-4a702edf8cdc3559-koxudaxi__local-data-api-1" has no exposed ports
Service container logs:
*********
```
