### ISSUE TITLE
Is this accessing an actually Aurora Serverless Instance running in a VPC?

### ISSUE THREAD

**Issue by marchant** [koxudaxi/local-data-api#35]
Or is it creating a local DB that responds to the http based Data API to run local tests? Have you tested it with something like aws-sdk for node.js? Thanks!

**Comment by koxudaxi** [comment]
> Is this accessing an actually Aurora Serverless Instance running in a VPC?

No. However, The local-data-api can access actually Aurora Serverless Instance by a setting.

> Or is it creating a local DB that responds to the http based Data API to run local tests? 

Yes, I show you docker-compose.yml for accessing local MySQL container.
Also, local-api-api can connect other real databases to include Aurora. 
```
version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
        - "3306:3306"
```

> Have you tested it with something like aws-sdk for node.js? Thanks!
Yes, I have not tested it with aws-SDK, I have tested only boto3(python3) and awscli
However, if you can change the endpoint URL  then, any client can use local-data-api.

You can change the endpoint to the local-data-api URL in the constructor.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#constructor-property

> endpoint (String) — The endpoint URI to send requests to. The default endpoint is built from the configured region. The endpoint should be a string like 'https://{service}.{region}.amazonaws.com'.
