### ISSUE TITLE
JVM Crashes

### ISSUE THREAD

**Issue by mimattan** [koxudaxi/local-data-api#38]
**Describe the bug**
When performing the execute-statement request, I get the following error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7168a9d0f9, pid=74, tid=0x00007f71707e4b88
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.13.0
# Distribution: Custom build (Tue Oct  1 11:00:28 UTC 2019)
# Problematic frame:
# C  [_jpype.cpython-37m-x86_64-linux-gnu.so+0x430f9]  JPJavaEnv::NewLocalRef(_jobject*)+0x9
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /app/hs_err_pid74.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```

**To Reproduce**
1. Start the docker image: 
`run --rm -it --name my-data-api -p 8080:80  -e MYSQL_HOST=127.0.0.1 -e MYSQL_PORT=3306 -e MYSQL_USER=root -e MYSQL_PASSWORD= -e RESOURCE_ARN=arn:aws:rds:us-east-1:123456789012:cluster:dummy -e SECRET_ARN=arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy koxudaxi/local-data-api`
2. Perform a request: 
`aws --endpoint-url http://127.0.0.1:8080 rds-data execute-statement --resource-arn "arn:aws:rds:us-east-1:123456789012:cluster:dummy" --sql "show databases"  --secret-arn "arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy" --database 'test'
`

**Expected behavior**
The Local Data API should return some data.
Does anyone have any idea what could be the root cause of this issue?

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by koxudaxi** [comment]
@mimattan 
> MYSQL_HOST=127.0.0.1 

The IP may be an invalid address, which I think is a local machine address.
local-data-api is not local, which is in a docker container.
local-data-api could not access to local(127.0.0.1) from a container. It is another network.

Cloud you use MySQL container?
Or, You have to change the network setting on a container.

BTW, the crash message is not user-friendly.
I want to change it to a better one in the future.

**Comment by ernestasdeveloper** [comment]
Facing the same problem

> 
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd84c48f0f9, pid=12, tid=0x00007fd8541cbb88
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.13.0
# Distribution: Custom build (Tue Oct  1 11:00:28 UTC 2019)
# Problematic frame:
# C  [_jpype.cpython-37m-x86_64-linux-gnu.so+0x430f9]  JPJavaEnv::NewLocalRef(_jobject*)+0x9
> 

when running command in cli:
`aws --endpoint-url 'http://127.0.0.1:10001' rds-data execute-statement --database 'test_db' --resource-arn 'test_resource_arn' --secret-arn 'test_secrect_arn' --sql 'CREATE TABLE TEST(id Int)'` 

using docker-compose:
`version: '3.1'

services:
  database:
    image: mysql:5.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: test_psw
    volumes:
    - ../aws/rds/sql:/docker-entrypoint-initdb.d
    ports:
      - "3360:3306"
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test_psw
      RESOURCE_ARN: test_resource_arn
      SECRET_ARN: test_secrect_arn
    ports:
      - "8080:80"
    depends_on:
      - database`

**Comment by koxudaxi** [comment]
@ernestasdeveloper 
Thank you for reporting an error.

I have tested your steps, which wrote here, after remove all images container.
It was success.
```bash
$ aws --endpoint-url 'http://127.0.0.1:8080' rds-data execute-statement --database 'test_db' --resource-arn 'test_resource_arn' --secret-arn 'test_secrect_arn' --sql 'CREATE TABLE TEST(id Int)'
{
    "generatedFields": [],
    "numberOfRecordsUpdated": 0
}

```
of course, I used your `docker-compose.yml`.
My machine is Ubuntu 18.04.
I don't know why you got an error. I try to test on Mac.

**Comment by mimattan** [comment]
Hi @koxudaxi 

I also have this issue on a Mac.

**Comment by koxudaxi** [comment]
I have run the same test on my Mac.
The result is a success.

I show you all the information in my environment.
macOS: 10.13.6

Docker version
```shell
$ docker info | grep Version                  
 Server Version: 19.03.4
 Kernel Version: 4.9.184-linuxkit
````

awscli version
```shell
$ aws --version                                     
aws-cli/1.16.283 Python/3.7.3 Darwin/17.7.0 botocore/1.13.19
```

remove all containers and images manually.
```shell
$ docker rm -f `docker ps -a |awk '{print $1}'`
$ docker image rm -f ` docker  images |awk '{print $3}'`
```

I think local-data-api must detail the message for debugging.

**Comment by cjjenkinson** [comment]
I also have this error

```
version: "3.1"

services:
  local-data-api:
    image: koxudaxi/local-data-api:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: "arn:aws:rds:us-east-1:123456789012:cluster:dummy"
      SECRET_ARN: "arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy"
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fulfilment
    ports:
      - "3306:3306"
````

AWS Cli
```
aws-cli/1.16.253 Python/2.7.10 Darwin/18.2.0 botocore/1.12.243
```


On OSX
