### ISSUE TITLE
Using README instructions, receiving `botocore.exceptions.ClientError`

### ISSUE THREAD

**Issue by pzula** [koxudaxi/local-data-api#74]
**Describe the bug**

Using the README instructions for a `docker-compose.yml` file for Postgres settings, I receive the following error when executing the test commands in the README:

```
botocore.exceptions.ClientError: An error occurred (500) when calling the ExecuteStatement operation (reached max retries: 4): Internal Server Error
```

**To Reproduce**

The README describes setup for the `docker-compose.yml` file for Postgres as follows, which I am using:

```
version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      ENGINE: PostgreSQLJDBC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports:
        - "5432:5432"
```

In my python environment, I have the `boto3` package with version `==1.13.7`. My python version is `3.7`.

I run `docker-compose up -d` and see the containers running with the right ports.

In my python environment, I start a python shell and run the following commands:

```
>>> import boto3; client = boto3.client('rds-data', endpoint_url='http://127.0.0.1:8080', aws_access_key_id='aaa',  aws_secret_access_key='bbb')
>>> client.execute_statement(resourceArn='arn:aws:rds:us-east-1:123456789012:cluster:dummy', secretArn='arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy', sql='show databases', database='test')

```

The result is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.local/share/virtualenvs/writer-lr1TS-R9/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/.local/share/virtualenvs/writer-lr1TS-R9/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the ExecuteStatement operation (reached max retries: 4): Internal Server Error
```

**Expected behavior**

I expect `execute_statement` command to return a valid response instead of an error, as shown in the README example.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2

**Additional context**
In my python environment, I have the `boto3` package with version `==1.13.7`. My python version is `3.7`.
