### ISSUE TITLE
Not able to run any SQL Query against local-data-api docker image on Mac Machine

### ISSUE THREAD

**Issue by healthpraxone** [koxudaxi/local-data-api#77]
**Describe the bug**
Not able to run any SQL Query against local-data-api docker image

**To Reproduce**
1. Create new file named docker-compose-local-db.yml
2. Copy the following content in the yml file 
```
version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
        - "3306:3306"
```
3. save file
4. run command in terminal window
`docker-compose  -f docker-compose-local-db.yml up`
5. docker is up and running
6. run following command in other terminal window
`aws --endpoint-url http://127.0.0.1:8080 rds-data execute-statement --resource-arn "arn:aws:rds:us-east-1:123456789012:cluster:dummy" --sql "show databases"  --secret-arn "arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy" --database 'test'`

7. Following error coming in the terminal

`

An error occurred (404) when calling the ExecuteStatement operation: <!DOCTYPE html>
\<html lang="en">
\<head>
\<meta charset="utf-8">
\<title>Error</title>
\</head>
\<body>
\<pre>Cannot POST /Execute</pre>
\</body>
\</html>

`

**Expected behavior**
No Error running SQL command against local mysql server

**Desktop (please complete the following information):**
 - OS: MAC OS 

docker info | grep Version
 Server Version: 19.03.13
 Kernel Version: 4.19.76-linuxkit

aws --version 
aws-cli/2.0.50 Python/3.8.5 Darwin/19.6.0 source/x86_64
