### ISSUE TITLE
Getting "detail": "Not found"

### ISSUE THREAD

**Issue by jgomes94** [koxudaxi/local-data-api#87]
**Describe the bug**
I have the docker compose as follows:
version: "3.1"

```
services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:725695492778:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:725695492778:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
```

**To Reproduce**
1. docker-compose up -d
2. Postman Request to get to http://127.0.0.1:8080 without any params. 

And I get everytime ' "detail": "Not Found"'. I have tried to access it programatically in a Node JS env and it's the same everytime i get '"detail": "Not Found", no matter what I try. 

The log that I see in the docker is:
![image](https://user-images.githubusercontent.com/32710158/108093372-91879b00-7075-11eb-9d66-2c67f169bf95.png)

It just gets 404, i've been strugling with this for a few days any help is much appreciated!

PS: I know the mysql database is created as I tried to connect via workbench and its there.

Thanks a lot in advance

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
Would you show me the code for a client-side?
I guess "detail": "Not Found" was returned by `local-data-api`.
But, The client accessed to `/` . the root path is undefined in ` local-data-api`.
The local-data-api expect access like `/Execute`

https://github.com/koxudaxi/local-data-api/blob/2c58206f0221c913521778c627ed2bdbff11d274/local_data_api/main.py#L73-L78

**Comment by jgomes94** [comment]
Thanks for quick reply koxudaxi, you are right, I tried the /Execute and it answered me "detail":"Method not allowed", which makes more sense since i didn't set any params.

My client code looks like this:

```
import { APIGatewayProxyResult } from 'aws-lambda';
import Client = require('data-api-client');

export const lambdaHandler = async (): Promise<APIGatewayProxyResult> => {
    try {
        let connection = Client({
            secretArn: 'arn:aws:secretsmanager:us-east-1:725695492778:secret:dummy',
            resourceArn: 'arn:aws:rds:us-east-1:725695492778:cluster:dummy',
            database: 'test',
            region: 'eu-west-1',
            options: {
                endpoint: 'http://127.0.0.1:8080',
            }
        })

        let res = await connection.query('SELECT * FROM cards');
        console.log('res!!', res);
    } catch (exception) {
        return { body: `{exception: ${exception.stack}}`, statusCode: 500 };
    }

    return { body: `{success: true}`, statusCode: 200 };
};
```
I am using it to simulate locally an AWS lambda. And i get this cyptic stack trace when i run the code:
![image](https://user-images.githubusercontent.com/32710158/108200951-15459400-7117-11eb-9c02-02b7a2846ab0.png)

which comes from the "Exception".

I realize that it also doesn't show any entry in the docker container, so it's possible that it is not even reaching the container at all.

Anyway any help/ideas are much appreciated

**Comment by koxudaxi** [comment]
I think this problem came from the client settings
Have you read this comment yet?
https://github.com/jeremydaly/data-api-client/issues/79#issuecomment-768126882

Also, you can check to able to connect to it with aws-cli.
https://github.com/koxudaxi/local-data-api#how-to-use-this-image

**Comment by jgomes94** [comment]
hi @koxudaxi I've tried to solution, however, it did not work. 

I am suspicious that is something with the AWS SDK. I tried to use the function from the SDK itself and I get the same error. And even in that I still didn't get the log on the docker that a request arrived. 

I'll close this issue and try with the AWS SDK team as I feel this is something with it.
Thanks for your help @koxudaxi

**Comment by koxudaxi** [comment]
@jgomes94 
I have tried your example.
The result is a success.

```yaml
version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:725695492778:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:725695492778:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
        - "3306:3306"

```

sample.ts
```typescript
import Client = require('data-api-client');


function f() {
     let connection = Client({
    secretArn: 'arn:aws:secretsmanager:us-east-1:725695492778:secret:dummy',
    resourceArn: 'arn:aws:rds:us-east-1:725695492778:cluster:dummy',
    database: 'test',
    region: 'eu-west-1',
    options: {
        endpoint: 'http://127.0.0.1:8080',
    }
    })

    connection.query('show databases').then(
     res =>
    console.log('res!!', res)
    )

}
f()
```

```bash
$ ts-node sample.ts
res!! {
  records: [
    { Database: 'information_schema' },
    { Database: 'mysql' },
    { Database: 'performance_schema' },
    { Database: 'test' }
  ]
}

```
